Repository 4teamwork/opengever.core, pull requests merged in 2018-10, with the labels that each got.

#4924 Ignore Tika exceptions during indexing in Solr
  docs/HISTORY.txt
  solr-conf/solrconfig.xml
Labels: Backport needed

#4923 Fix some french translations
  opengever/base/locales/de/LC_MESSAGES/opengever.base.po
  opengever/base/locales/de/LC_MESSAGES/plone.po
  opengever/base/locales/fr/LC_MESSAGES/opengever.base.po
  opengever/base/locales/fr/LC_MESSAGES/plone.po
  opengever/base/locales/opengever.base.pot
  opengever/base/locales/plone.pot
  opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
Labels: Backport needed

#4921 Fix bumblebee overlay link for not yet created initial version.
  docs/HISTORY.txt
  opengever/document/browser/versions_tab.py
  opengever/document/tests/test_versions_tab.py
  opengever/tabbedview/helper.py
Labels: Backport needed

#4941 Revoke temporary roles also when closing direct-execution tasks.
  docs/HISTORY.txt
  opengever/task/__init__.py
  opengever/task/tests/test_localroles.py
Labels: Backport needed

#4916 Allow users to retry creating a file from a Oneoffixx template
  docs/HISTORY.txt
  opengever/document/browser/actionbuttons.py
  opengever/document/browser/templates/macros.pt
  opengever/document/document.py
  opengever/document/locales/de/LC_MESSAGES/opengever.document.po
  opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
  opengever/document/locales/opengever.document.pot
  opengever/document/static/officeconnector.js
  opengever/oneoffixx/tests/test_oneoffixx.py
Labels: OneOffixx

#4948 Test no settings or features share a name
  opengever/base/tests/test_get_setting_view.py
Labels: OneOffixx

#4968 Fix sharing form local_roles inheritance fallback.
  docs/HISTORY.txt
  opengever/sharing/browser/sharing.py
  opengever/sharing/tests/test_sharing.py
Labels: Backport needed

#4982 Sharing form fixes
  docs/HISTORY.txt
  opengever/base/role_assignments.py
  opengever/sharing/browser/resources/sharing.js
  opengever/sharing/browser/sharing.py
  opengever/sharing/tests/test_sharing.py
Labels: Backport needed

#5027 Remove wrong divider symbols in the mergefields docu.
  docs/public/admin-manual/meeting/mergefields.rst
Labels: Documentation
