Repository 4teamwork/opengever.core, pull requests merged in 2018-09, with the labels that each got.

#4817 Fix handling of unidirectional by ref tasks in a sequential process.
  docs/HISTORY.txt
  opengever/task/handlers.py
  opengever/task/tests/test_sequential_task_process.py
Labels: Backport needed

#4821 Fix double escaping of agendaitem title in meeting overview.
  docs/HISTORY.txt
  opengever/meeting/browser/meetings/templates/navigation.html
Labels: Backport needed

#4822 Fix an encoding issue by not using model code.
  docs/HISTORY.txt
  opengever/core/upgrades/20180619143343_make_sure_excerpt_document_title_is_unicode/upgrade.py
Labels: Backport needed, Bug

#4823 Scale down size for logo wrapper, to have more space for personal menues
  docs/HISTORY.txt
  plonetheme/teamraum/resources/index.html
Labels: Backport needed

#4843 Fix global scoped "show more" links for SOLR livesearch
  docs/HISTORY.txt
  opengever/base/browser/livesearch.py
  opengever/base/tests/test_search.py
Labels: Backport needed

#4864 Register bmp as editable by officeconnector type.
  docs/HISTORY.txt
  opengever/core/profiles/default/registry.xml
  opengever/core/upgrades/20180907161827_extend_officeconnector_editable_file_types/__init__.py
  opengever/core/upgrades/20180907161827_extend_officeconnector_editable_file_types/registry.xml
  opengever/core/upgrades/20180907161827_extend_officeconnector_editable_file_types/upgrade.py
Labels: Backport needed

#4836 Konkretisierung neu zuweisen und Aufgabe delgieren
  docs/public/user-manual/aufgaben/empfangene_bearbeiten.rst
Labels: Documentation

#4847 Ergänzung mehrere ad hoc Anträge; Sitzungen kommentieren; Sitzungsvorlagen
  docs/public/admin-manual/img/media/img-sitzungsvorlage-1.png
  docs/public/admin-manual/img/media/img-sitzungsvorlage-2.png
  docs/public/admin-manual/img/media/img-sitzungsvorlage-3.png
  docs/public/admin-manual/img/media/img-sitzungsvorlage-4.png
  docs/public/admin-manual/img/media/img-sitzungsvorlage-5.png
  docs/public/admin-manual/img/media/img-sitzungsvorlage-6.png
  docs/public/admin-manual/img/media/img-sitzungsvorlage-7.png
  docs/public/admin-manual/img/media/img-sitzungsvorlage-8.png
  docs/public/admin-manual/meeting/index.rst
  docs/public/admin-manual/meeting/sitzungsvorlage.rst
  docs/public/user-manual/dokumente/bearbeiten.rst
  docs/public/user-manual/img/media/img-spvupdate-12.png
  docs/public/user-manual/spv/antrag-erfassen.rst
  docs/public/user-manual/spv/sitzung-durchfuehren.rst
Labels: Documentation

#4866 Add missing mimetype for wmf files.
  docs/HISTORY.txt
  opengever/core/upgrades/20180911140637_fix_contenttype_for_ms_publisher_files/__init__.py
  opengever/core/upgrades/20180911140637_fix_contenttype_for_ms_publisher_files/upgrade.py
  opengever/document/extra_mimetypes.py
Labels: Backport needed

#4871 No longer use catalog.reindexObject.
  docs/HISTORY.txt
  opengever/base/handlers.py
  opengever/bundle/console.py
  opengever/core/upgrades/20180912160954_reindex_checked_out_and_allowed_roles_and_users_on_solr/__init__.py
  opengever/core/upgrades/20180912160954_reindex_checked_out_and_allowed_roles_and_users_on_solr/upgrade.py
  opengever/document/checkout/manager.py
  opengever/setup/overrides.zcml
  opengever/setup/sections/reindexobject.py
  opengever/usermigration/creator.py
Labels: Backport needed

#4874 Fix groubmembers overlay for groupids with spaces.
  docs/HISTORY.txt
  opengever/sharing/browser/sharing.py
  opengever/sharing/tests/test_sharing.py
Labels: Backport needed

#4867 Support adding task via REST API
  docs/HISTORY.txt
  opengever/activity/tests/test_handlers.py
  opengever/inbox/forwarding.py
  opengever/inbox/tests/test_activities.py
  opengever/inbox/tests/test_inbox_assign.py
  opengever/ogds/base/sources.py
  opengever/task/browser/accept/utils.py
  opengever/task/browser/forms.py
  opengever/task/configure.zcml
  opengever/task/handlers.py
  opengever/task/tests/test_activities.py
  opengever/task/tests/test_api_support.py
  opengever/task/tests/test_comment_response.py
Labels: API

#4884 Fix task and activity queries for oracle backends
  docs/HISTORY.txt
  opengever/activity/center.py
  opengever/activity/model/query.py
  opengever/globalindex/model/query.py
Labels: Backport needed

#4891 Docs: Aussonderung FR hinzugefügt
  docs/public-fr/_static/img/img-triage-1.png
  docs/public-fr/_static/img/img-triage-2.png
  docs/public-fr/_static/img/img-triage-3.png
  docs/public-fr/_static/img/img-triage-4.png
  docs/public-fr/_static/img/img-triage-5.png
  docs/public-fr/_static/img/img-triage-6.png
  docs/public-fr/chapitre9-triage.rst
  docs/public-fr/index.rst
Labels: Documentation

#4894 Bump ftw.keywordwidget to 1.5.2 version.
  versions.cfg
Labels: Backport needed

#4895 Split search terms at non-alphanumeric characters
  docs/HISTORY.txt
  solr-conf/managed-schema
Labels: Backport needed

#4897 Textkorrektur bei Teams verwalten
  docs/public/admin-manual/teams.rst
Labels: Documentation

#4898 Bump ftw.mail to 2.5.5
  opengever/mail/mail.py
  versions.cfg
Labels: Backport needed

#4896 Bump Lucene version used in Solr to 7.3.1
  docs/HISTORY.txt
  solr-conf/solrconfig.xml
Labels: Backport needed

#4899 Bump ftw.solr and ftw.recipe.solr to latest version.
  versions.cfg
Labels: Backport needed

#4900 Clump all the remaining functional tests to the same CI build
  test-plone-4.3.x-functional.cfg
  test-plone-4.3.x.cfg
Labels: Testing

#4912 Only allow adding meeting templates, when meeting feature is enabled.
  docs/HISTORY.txt
  opengever/dossier/templatefolder/templatefolder.py
  opengever/dossier/tests/test_templatefolder.py
Labels: Backport needed

#4914 Enable the meeting feature for meeting template tests
  opengever/meeting/tests/test_meeting_template.py
Labels: Backport needed
