Repository 4teamwork/opengever.core, pull requests merged in 2018-07, with the labels that each got.

#4519 Fix unicode error in versions tab comments.
  docs/HISTORY.txt
  opengever/document/browser/versions_tab.py
  opengever/document/tests/test_versions_tab.py
  opengever/journal/tab.py
  opengever/journal/tests/test_journal_tab.py
  opengever/tabbedview/helper.py
  opengever/testing/helpers.py
Labels: Bug

#4514 Tests: Add default value tests for REST API content creation.
  opengever/base/tests/test_default_values_for_types.py
Labels: Default-values

#4518 Fix a bug with modern emojis in task responses.
  docs/HISTORY.txt
  opengever/task/browser/overview.py
  opengever/task/viewlets/response.py
Labels: Bug

#4529 Untangle admin units and org units in FixtureBuilder for functional test cases
  opengever/activity/tests/test_plone_center.py
  opengever/base/tests/test_default_values_for_types.py
  opengever/base/tests/test_oguid.py
  opengever/base/tests/test_transport.py
  opengever/base/transport.py
  opengever/disposition/tests/test_activities.py
  opengever/disposition/tests/test_sippackage.py
  opengever/globalindex/tests/test_reporter.py
  opengever/globalindex/tests/test_task_css_class.py
  opengever/globalindex/tests/test_task_link.py
  opengever/inbox/tests/test_accept.py
  opengever/inbox/tests/test_activities.py
  opengever/inbox/tests/test_inbox.py
  opengever/inbox/tests/test_inbox_assign.py
  opengever/inbox/tests/test_inbox_container.py
  opengever/inbox/tests/test_overview.py
  opengever/inbox/tests/test_tabs.py
  opengever/inbox/tests/test_yearfolder.py
  opengever/latex/tests/test_listing.py
  opengever/latex/tests/test_opentaskreport.py
  opengever/meeting/browser/sablontemplate.py
  opengever/meeting/tests/test_committee_roles.py
  opengever/meeting/tests/test_protocol_json_data.py
  opengever/ogds/base/tests/test_sort_helpers.py
  opengever/ogds/base/tests/test_sources.py
  opengever/task/tests/test_activities.py
  opengever/task/tests/test_assign_to_dossier.py
  opengever/task/tests/test_deadline_modification.py
  opengever/task/tests/test_forms.py
  opengever/task/tests/test_indexer.py
  opengever/task/tests/test_localroles.py
  opengever/task/tests/test_main.py
  opengever/task/tests/test_redirector.py
  opengever/task/tests/test_response_descriptions.py
  opengever/task/tests/test_response_syncer.py
  opengever/task/tests/test_responsetransporter.py
  opengever/task/tests/test_successor.py
  opengever/task/tests/test_task.py
  opengever/task/tests/test_transition_actions.py
  opengever/task/tests/test_workflow.py
  opengever/testing/builders/dx.py
  opengever/testing/builders/fixture.py
  opengever/testing/builders/sql.py
  opengever/usermigration/tests/test_ogds_migrator.py
Labels: tech debt

#4534 Open task report: Fix condition to report admin-unit local tasks only
  docs/HISTORY.txt
  opengever/latex/opentaskreport.py
  opengever/latex/tests/test_opentaskreport.py
Labels: API, Bug

#4573 Fix issue where empty version comments caused version tab to fail
  docs/HISTORY.txt
  opengever/document/tests/test_versions_tab.py
  opengever/tabbedview/helper.py
  opengever/tabbedview/tests/test_helpers.py
Labels: Bug

#4590 Docs: Check whether git-lfs is enabled before building.
  bin/enable-lfs
  sphinx.cfg
Labels: Documentation

#4547 Rewrite API tests as integration tests
  opengever/api/tests/test_content_creation.py
  opengever/base/tests/test_default_values_for_types.py
Labels: Testing

#4594 Docs: Struktur für Release-Notes
  docs/intern/conf.py
  docs/intern/meta.rst
  docs/public-fr/conf.py
  docs/public/_static/img/img-release-notes-3.5-1.png
  docs/public/_static/img/img-release-notes-3.5-2.png
  docs/public/_static/img/img-release-notes-3.5-3.png
  docs/public/_static/img/img-release-notes-3.5-4.png
  docs/public/_static/img/img-release-notes-3.5-5.png
  docs/public/conf.py
  docs/public/index.rst
  docs/public/release-notes/archiv/index.rst
  docs/public/release-notes/archiv/release-2.4.1.rst
  docs/public/release-notes/archiv/release-2.4.rst
  docs/public/release-notes/archiv/release-2.5.1.rst
  docs/public/release-notes/archiv/release-2.5.2.rst
  docs/public/release-notes/archiv/release-2.5.3.rst
  docs/public/release-notes/archiv/release-2.5.rst
  docs/public/release-notes/archiv/release-2.6.rst
  docs/public/release-notes/archiv/release-2.7.rst
  docs/public/release-notes/archiv/release-2.8.rst
  docs/public/release-notes/archiv/release-2.9.rst
  docs/public/release-notes/archiv/release-3.1.rst
  docs/public/release-notes/archiv/release-3.10.rst
  docs/public/release-notes/archiv/release-3.11.rst
  docs/public/release-notes/archiv/release-3.2.rst
  docs/public/release-notes/archiv/release-3.3.rst
  docs/public/release-notes/archiv/release-3.4.rst
  docs/public/release-notes/archiv/release-3.5.1.rst
  docs/public/release-notes/archiv/release-3.5.rst
  docs/public/release-notes/archiv/release-3.6.rst
  docs/public/release-notes/archiv/release-3.7.rst
  docs/public/release-notes/archiv/release-3.8.rst
  docs/public/release-notes/archiv/release-3.9.rst
  docs/public/release-notes/archiv/release-3.rst
  docs/public/release-notes/index.rst
  docs/public/release-notes/release-2017.1.rst
  docs/public/release-notes/release-2017.2.rst
  docs/public/release-notes/release-2017.3.rst
  docs/public/release-notes/release-2017.4.rst
  docs/public/release-notes/release-2017.5.rst
  docs/public/release-notes/release-2017.6.rst
  docs/public/release-notes/release-2017.7.rst
  docs/public/release-notes/release-2018.1.rst
  docs/public/release-notes/release-2018.2.rst
  docs/public/release-notes/release-2018.3.rst
  sphinx.cfg
Labels: Documentation

#4600 Docs: Fix ordering of release notes in TOC.
  docs/public/release-notes/index.rst
Labels: Documentation

#4618 Sequentielle Abläufe
  docs/public/admin-manual/img/media/img-standardablauf-30.png
  docs/public/admin-manual/img/media/img-standardablauf-31.png
  docs/public/admin-manual/standardablauferstellen.rst
  docs/public/user-manual/aufgaben/aufgaben-workflow.rst
  docs/public/user-manual/aufgaben/empfangene_bearbeiten.rst
  docs/public/user-manual/aufgaben/erstellen.rst
  docs/public/user-manual/img/media/img-aufgaben-workflow-1.png
  docs/public/user-manual/img/media/img-standardablauf-3.png
  docs/public/user-manual/img/media/img-standardablauf-32.png
  docs/public/user-manual/img/media/img-standardablauf-33.png
  docs/public/user-manual/img/media/img-standardablauf-34.png
  docs/public/user-manual/img/media/img-standardablauf-35.png
  docs/public/user-manual/img/media/img-standardablauf-36.png
  docs/public/user-manual/img/media/img-standardablauf-37.png
  docs/public/user-manual/img/media/img-standardablauf-38.png
  docs/public/user-manual/img/media/img-standardablauf-4.png
  docs/public/user-manual/img/media/img-standardablauf-5.png
  docs/public/user-manual/img/media/img-standardablauf-6.png
  docs/public/user-manual/standardablaeufe.rst
Labels: Documentation

#4635 Anpassung Seq-Abläufe gemäss Inputs Su
  docs/public/admin-manual/standardablauferstellen.rst
  docs/public/user-manual/img/media/img-standardablauf-1.png
  docs/public/user-manual/standardablaeufe.rst
Labels: Documentation
