Repository 4teamwork/opengever.core, pull requests merged in 2018-08, with the labels that each got.

#4661 Bump docxcompose to version 1.0.0.a11
  docs/HISTORY.txt
  versions.cfg
Labels: Backport needed

#4625 Doku Anpassungen durch OGIP 36
  docs/public/user-manual/benachrichtigung.rst
  docs/public/user-manual/img/media/img-benachrichtigungs-einstellungen-5.png
  docs/public/user-manual/spv/antrag-erfassen.rst
  docs/public/user-manual/spv/antrag-traktandieren.rst
  docs/public/user-manual/spv/antrags-benachrichtigungen.rst
  docs/public/user-manual/spv/index.rst
Labels: Documentation

#4627 Doku Änderungen OGIP 45; Emojis bei Tipps und Tricks
  docs/public/admin-manual/img/media/img-rollenmodell-1.png
  docs/public/admin-manual/rollenmodell.rst
  docs/public/user-manual/aufgaben/aufgaben-workflow.rst
  docs/public/user-manual/aufgaben/erstellen.rst
  docs/public/user-manual/dokumente/bearbeiten.rst
  docs/public/user-manual/img/media/img-grundlagen-40.png
  docs/public/user-manual/tippsundtricks.rst
Labels: Documentation

#4678 Task forms: Drop unnecessary distinction between single/multi org unit setups
  docs/HISTORY.txt
  opengever/task/browser/assign.py
  opengever/task/browser/forms.py
  opengever/task/locales/de/LC_MESSAGES/opengever.task.po
  opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
  opengever/task/locales/opengever.task.pot
  opengever/task/task.py
Labels: tech debt

#4674 Only prefill dossier_manager as a form level default (instead of schema level)
  docs/HISTORY.txt
  opengever/base/tests/test_default_values_for_types.py
  opengever/dossier/behaviors/protect_dossier.py
  opengever/dossier/browser/forms.py
  opengever/dossier/tests/test_protect_dossier.py
Labels: Bug

#4696 Add Release-Notes "3.3" to Docs
  docs/public/_static/img/img-release-notes-3.3-1.png
  docs/public/_static/img/img-release-notes-3.3-2.png
  docs/public/release-notes/archiv/release-3.3.rst
Labels: Documentation

#4698 Add Release-Notes "3.4" to Docs
  docs/public/_static/img/img-release-notes-3.4-1.png
  docs/public/_static/img/img-release-notes-3.4-2.png
  docs/public/_static/img/img-release-notes-3.4-3.png
  docs/public/_static/img/img-release-notes-3.4-4.png
  docs/public/release-notes/archiv/release-3.4.rst
Labels: Documentation

#4700 Add Release-Notes "3.5.3" to Docs
  docs/public/_static/img/img-release-notes-3.5.3-1.png
  docs/public/release-notes/archiv/release-3.5.3.rst
Labels: Documentation

#4706 Add Release-Notes "3.6" to Docs
  docs/public/release-notes/archiv/release-3.6.rst
Labels: Documentation

#4707 Add Release-Notes "3.7" to Docs
  docs/public/release-notes/archiv/release-3.7.rst
Labels: Documentation

#4695 Add Release-Notes "3.2" to Docs
  docs/public/release-notes/archiv/release-3.2.rst
Labels: Documentation

#4713 Add Release-Notes "3.8" to Docs
  docs/public/_static/img/img-release-notes-3.8-1.png
  docs/public/_static/img/img-release-notes-3.8-2.png
  docs/public/_static/img/img-release-notes-3.8-3.png
  docs/public/_static/img/img-release-notes-3.8-4.png
  docs/public/_static/img/img-release-notes-3.8-5.png
  docs/public/_static/img/img-release-notes-3.8-6.png
  docs/public/release-notes/archiv/release-3.8.rst
Labels: Documentation

#4714 Add Release-Notes "3.9" to Docs
  docs/public/_static/img/img-release-notes-3.9-1.png
  docs/public/_static/img/img-release-notes-3.9-2.png
  docs/public/_static/img/img-release-notes-3.9-3.png
  docs/public/_static/img/img-release-notes-3.9-4.png
  docs/public/_static/img/img-release-notes-3.9-5.png
  docs/public/_static/img/img-release-notes-3.9-6.png
  docs/public/release-notes/archiv/release-3.9.rst
Labels: Documentation

#4716 Add Release-Notes "2018.4" to Docs
  docs/public/_static/img/img-release-notes-2018.4-1.png
  docs/public/_static/img/img-release-notes-2018.4-2.png
  docs/public/_static/img/img-release-notes-2018.4-3.png
  docs/public/release-notes/index.rst
  docs/public/release-notes/release-2018.4.rst
Labels: Documentation

#4719 Add Release-Notes "3.10" to Docs
  docs/public/_static/img/img-release-notes-3.10-1.png
  docs/public/_static/img/img-release-notes-3.10-2.png
  docs/public/release-notes/archiv/release-3.10.rst
Labels: Documentation

#4721 Add Release-Notes "3.11" to Docs
  docs/public/release-notes/archiv/release-3.11.rst
Labels: Documentation

#4739 Make sure widgets properly return persisted missing values
  docs/HISTORY.txt
  opengever/base/monkey/patches/__init__.py
  opengever/base/monkey/patches/default_values.py
  opengever/base/tests/test_default_values_for_types.py
  opengever/testing/helpers.py
Labels: Default-values

#4812 Make upgrade step 20180619143343 deferrable:
  docs/HISTORY.txt
  opengever/core/upgrades/20180619143343_make_sure_excerpt_document_title_is_unicode/upgrade.py
Labels: Backport needed
