Repository 4teamwork/opengever.core, pull requests merged in 2018-04, with the labels that each got.

#4145 Fix logout worker when using SSO
  docs/HISTORY.txt
  opengever/base/browser/resources/logoutClient.js
  opengever/base/browser/resources/logoutWorker.js
Labels: Backport needed

#4144 Fix datetime picker when adding a new meeting.
  docs/HISTORY.txt
  opengever/meeting/browser/resources/datetimepicker.js
Labels: Backport needed

#4149 Use latest ftw.datetimepicker version
  opengever/meeting/browser/resources/datetimepicker.js
  versions.cfg
Labels: Backport needed

#4165 Update extends in policy templates.
  opengever/policytemplates/policy_template/opengever.+package.name+/versions.cfg.bob
Labels: Bug

#4196 Korrektur Text (Rechtschreibung)
  docs/public/user-manual/aufgaben/mandantenuebergreifende_zusammenarbeit.rst
Labels: Documentation

#4194 Konkretisierung Protokoll-Generierung
  docs/public/user-manual/spv/sitzung-abschliessen.rst
Labels: Documentation

#4189 Update dependencies
  docs/HISTORY.txt
  versions.cfg
Labels: tech debt

#4197 Ergänzung Workflow-Diagramm bei Aufgaben
  docs/public/user-manual/aufgaben/workflow.rst
  docs/public/user-manual/img/media/img-aufgaben-workflow-1.png
Labels: Documentation

#4199 Ergänzung Globale Rollen gemäss Marco
  docs/public/admin-manual/forcecheckin.rst
  docs/public/admin-manual/rollenmanager.rst
Labels: Documentation

#4215 Bump docxcompose version to 1.0.0a7.
  versions.cfg
Labels: Backport needed

#4225 Erstellung Kapitel für Zope Edit Manger OSX
  docs/public/systemadmin-manual/img/media/img-zem-1.png
  docs/public/systemadmin-manual/img/media/img-zem-2.png
  docs/public/systemadmin-manual/index.rst
  docs/public/systemadmin-manual/officeconnector/autoopenfiles.rst
  docs/public/systemadmin-manual/zope-edit-manager.rst
Labels: Documentation

#4053 Implement bumblebee's auto refresh functionality
  docs/HISTORY.txt
  opengever/api/config.py
  opengever/api/tests/test_config.py
  opengever/base/browser/configure.zcml
  opengever/base/browser/jsvariables.py
  opengever/base/browser/search.pt
  opengever/base/tests/test_jsvariables.py
  opengever/bumblebee/__init__.py
  opengever/bumblebee/browser/overlay.py
  opengever/bumblebee/browser/preview_listing.py
  opengever/bumblebee/browser/resources/bumblebee-cable.js
  opengever/bumblebee/browser/resources/bumblebee.js
  opengever/bumblebee/browser/templates/bumblebeeoverlay.pt
  opengever/bumblebee/browser/templates/previews.pt
  opengever/bumblebee/interfaces.py
  opengever/bumblebee/tests/test_preview_listing.py
  opengever/core/profiles/default/jsregistry.xml
  opengever/core/tests/test_view_security.py
  opengever/core/upgrades/20180202111739_register_bumblebee_cable_js/__init__.py
  opengever/core/upgrades/20180202111739_register_bumblebee_cable_js/jsregistry.xml
  opengever/core/upgrades/20180202111739_register_bumblebee_cable_js/upgrade.py
  opengever/core/upgrades/20180423163916_add_bumblebee_auto_refresh_feature_flag/__init__.py
  opengever/core/upgrades/20180423163916_add_bumblebee_auto_refresh_feature_flag/registry.xml
  opengever/core/upgrades/20180423163916_add_bumblebee_auto_refresh_feature_flag/upgrade.py
  opengever/document/browser/overview.py
  opengever/document/browser/templates/overview.pt
  opengever/document/widgets/tooltip.pt
  opengever/document/widgets/tooltip.py
  opengever/examplecontent/profiles/default/registry.xml
  opengever/testing/integration_test_case.py
Labels: Bumblebee

#4227 Split Kapitel Rollenmanager in Rollenmodell und Rollenmodell
  docs/public/admin-manual/index.rst
  docs/public/admin-manual/rollenmanager.rst
  docs/public/admin-manual/rollenmodell.rst
Labels: Documentation

#4228 Update OGIP-Prozess
  docs/intern/kurzreferenzen/ogip.rst
Labels: Documentation

#4238 Bump docxcompose to 1.0.0a8.
  docs/HISTORY.txt
  versions.cfg
Labels: Backport needed, Bug

#4236 Hervorhebung, dass ZEM nicht weiterentwickelt wird gemäss Input Pascal
  docs/public/systemadmin-manual/zope-edit-manager.rst
Labels: Documentation

#4226 Ergänzung Bemerkung zu möglichem Konflikt
  docs/public/admin-manual/forcecheckin.rst
  docs/public/admin-manual/img/media/img-forcecheckin-3.png
Labels: Documentation
