Repository 4teamwork/opengever.core, pull requests merged in 2018-11, with the labels that each got.

#5029 Ergänzung Kapitel Erinnerung setzen
  docs/public/user-manual/aufgaben/pendenzenkontrolle.rst
  docs/public/user-manual/img/media/img-aufgaben-39.png
Labels: Documentation

#5028 Ergänzung Journal-PDF nach Dossierabschluss
  docs/public/user-manual/dossiers/bearbeiten.rst
  docs/public/user-manual/img/media/img-dossiers-101.png
  docs/public/user-manual/img/media/img-dossiers-102.png
  docs/public/user-manual/img/media/img-dossiers-103.png
  docs/public/user-manual/img/media/img-dossiers-104.png
Labels: Documentation

#5079 Performance improvements on tasks local roles setter
  docs/HISTORY.txt
  opengever/base/role_assignments.py
  opengever/task/localroles.py
  opengever/task/tests/test_localroles.py
Labels: Aufgaben, Backport needed, performance

#5088 Fix revoke local roles performance improvement
  opengever/base/role_assignments.py
  opengever/task/tests/test_localroles.py
Labels: Backport needed

#5033 Erstellung Release Notes 2018.5
  docs/public/_static/img/img-release-notes-2018.5-1.png
  docs/public/release-notes/index.rst
  docs/public/release-notes/release-2018.5.rst
  docs/public/user-manual/aufgaben/pendenzenkontrolle.rst
  docs/public/user-manual/aufgaben/stellvertretung.rst
Labels: Documentation
