Repository 4teamwork/opengever.core, pull requests merged in 2018-03, with the labels that each got.

#4023 Update FF-Prozess
  docs/intern/kurzreferenzen/feedbackforum-prozess.rst
Labels: Documentation

#4012 Löschen von Zug-Spezifischen Abschluss-Regeln
  docs/public/user-manual/dossiers/bearbeiten.rst
Labels: Documentation

#4055 Update 2 Pics und Korr Satz
  docs/public/user-manual/aufgaben/mandantenuebergreifende_zusammenarbeit.rst
  docs/public/user-manual/img/media/img-mu-aufgaben-14.png
  docs/public/user-manual/img/media/img-mu-aufgaben-8.png
Labels: Documentation

#4058 Ergänzung Kapitel zur Aktivierung der 2FA
  docs/public/user-manual/grundlagen.rst
  docs/public/user-manual/img/media/img-grundlagen-29.png
  docs/public/user-manual/img/media/img-grundlagen-30.png
  docs/public/user-manual/img/media/img-grundlagen-31.png
Labels: Documentation

#4018 Improve input position for the transfer number
  docs/HISTORY.txt
  opengever/base/browser/gever_state.py
  opengever/base/interfaces.py
  opengever/base/tests/test_gever_state.py
  opengever/core/profiles/default/actions.xml
  opengever/core/upgrades/20180221144648_update_properties_action_available_expression/__init__.py
  opengever/core/upgrades/20180221144648_update_properties_action_available_expression/actions.xml
  opengever/core/upgrades/20180221144648_update_properties_action_available_expression/upgrade.py
  opengever/disposition/browser/configure.zcml
  opengever/disposition/browser/overview.py
  opengever/disposition/browser/resources/disposition.js
  opengever/disposition/browser/templates/overview.pt
  opengever/disposition/browser/views.py
  opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
  opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
  opengever/disposition/locales/opengever.disposition.pot
  opengever/disposition/tests/test_overview.py
  opengever/disposition/tests/test_views.py
Labels: Aussonderung

#4080 Fix force checkin button
  opengever/document/checkout/checkin.py
  opengever/document/locales/fr/LC_MESSAGES/opengever.document.po
  opengever/document/tests/test_checkout.py
Labels: Bug

#4066 Überarbeitung Doku: Hyperlinks setzten (wo möglich)
  docs/public/admin-manual/soft-delete.rst
  docs/public/user-manual/aufgaben/mandantenuebergreifende_zusammenarbeit.rst
  docs/public/user-manual/benachrichtigung.rst
  docs/public/user-manual/dokumente/ablegen.rst
  docs/public/user-manual/dokumente/bearbeiten.rst
  docs/public/user-manual/dokumente/diverseaktionen.rst
  docs/public/user-manual/dokumente/erstellen.rst
  docs/public/user-manual/dokumente/verwalten.rst
  docs/public/user-manual/dossiers/eroeffnen.rst
  docs/public/user-manual/dossiers/subdossiers.rst
  docs/public/user-manual/grundlagen.rst
  docs/public/user-manual/kontakte.rst
  docs/public/user-manual/meine_ablage.rst
  docs/public/user-manual/posteingang.rst
  docs/public/user-manual/spv/index.rst
  docs/public/user-manual/standardablaeufe.rst
  docs/public/user-manual/suchen.rst
Labels: Documentation

#4057 Überarbeitung Kapitel Pendenzenkontrolle und Erneuerung Printscreens
  docs/public/user-manual/aufgaben/pendenzenkontrolle.rst
  docs/public/user-manual/img/media/img-aufgaben-33.png
  docs/public/user-manual/img/media/img-aufgaben-34.png
  docs/public/user-manual/img/media/img-aufgaben-35.png
  docs/public/user-manual/img/media/img-aufgaben-36.png
  docs/public/user-manual/img/media/img-aufgaben-37.png
  docs/public/user-manual/img/media/img-aufgaben-38.png
Labels: Documentation
