Repository 4teamwork/opengever.core, pull requests merged in 2018-06, with the labels that each got.

#4404 Fix unicode error on proposal listings
  docs/HISTORY.txt
  opengever/meeting/browser/documents/proposalstab.py
  opengever/meeting/tests/test_proposal_listings.py
Labels: Backport needed

#4423 Update SPV änderungen protokollführung
  docs/public/user-manual/img/media/img-spvupdate-23.png
  docs/public/user-manual/spv/sitzung-durchfuehren.rst
  docs/public/user-manual/spv/sitzung-vorbereiten.rst
Labels: Documentation

#4427 Add support for properties to get_persisted_value_for_field() helper
  docs/HISTORY.txt
  opengever/base/default_values.py
  opengever/base/tests/test_default_values_for_types.py
Labels: Default-values

#4433 Ensure default values get set by patching DX DefaultAddForm.create
  docs/HISTORY.txt
  opengever/base/default_values.py
  opengever/base/monkey/patches/default_values.py
  opengever/base/tests/test_default_values_for_types.py
Labels: Default-values

#4441 Fix default value persistence edge case for title and description fields.
  docs/HISTORY.txt
  opengever/base/default_values.py
  opengever/base/monkey/patches/default_values.py
  opengever/base/tests/test_default_values_for_types.py
  opengever/meeting/proposal.py
Labels: Default-values

#4472 Theme: Remove diazo rule that duplicated some JS scripts.
  docs/HISTORY.txt
  opengever/base/browser/exposator.py
  opengever/base/viewlets/colorization.pt
  plonetheme/teamraum/resources/rules.xml
Labels: Bug, UI

#4479 Querverlinkung fr/de doku
  docs/public/conf.py
  docs/public/user-manual/index.rst
Labels: Documentation

#4478 Fix updating mail title via API.
  docs/HISTORY.txt
  opengever/api/mail.py
  opengever/api/tests/test_mail.py
Labels: Backport needed

#4473 Meeting zip export shall hande mails
  docs/HISTORY.txt
  opengever/meeting/browser/meetings/zipexport.py
  opengever/meeting/model/agendaitem.py
  opengever/meeting/tests/test_meeting_zipexport.py
Labels: Backport needed

#4477 Remove separate read permission for the `original_message` field
  docs/HISTORY.txt
  docs/schema-dumps/ftw.mail.mail.schema.json
  opengever/api/tests/test_mail.py
  opengever/mail/browser/mail.py
  opengever/mail/locales/de/LC_MESSAGES/ftw.mail.po
  opengever/mail/locales/de/LC_MESSAGES/opengever.mail.po
  opengever/mail/locales/fr/LC_MESSAGES/ftw.mail.po
  opengever/mail/locales/fr/LC_MESSAGES/opengever.mail.po
  opengever/mail/locales/ftw.mail.pot
  opengever/mail/locales/opengever.mail.pot
  opengever/mail/mail.py
  opengever/mail/tests/test_mail_overviewtab.py
Labels: Backport needed

#4506 Fix physical_path schema migration for oracle backends.
  docs/HISTORY.txt
  opengever/core/upgrades/20180517160709_change_physical_path_column_type/upgrade.py
Labels: Backport needed

#4512 Fixup for #4506 (oracle fix).
  opengever/core/upgrades/20180517160709_change_physical_path_column_type/upgrade.py
Labels: Backport needed

#4516 Increase size of the favorites plone_uid column.
  docs/HISTORY.txt
  opengever/base/model/__init__.py
  opengever/core/upgrades/20180403142317_add_favorites_table/upgrade.py
  opengever/core/upgrades/20180628121308_increase_uid_column_length_in_favorites_model/__init__.py
  opengever/core/upgrades/20180628121308_increase_uid_column_length_in_favorites_model/upgrade.py
Labels: Backport needed
