Repository 4teamwork/opengever.core, pull requests merged in 2018-12, with the labels that each got.

#5165 Bump docxcompose to have better reference support.
  docs/HISTORY.txt
  versions.cfg
Labels: Backport needed

#5174 Fix task revoking permissions on close/reassign
  docs/HISTORY.txt
  opengever/task/locales/de/LC_MESSAGES/opengever.task.po
  opengever/task/locales/fr/LC_MESSAGES/opengever.task.po
  opengever/task/locales/opengever.task.pot
  opengever/task/localroles.py
  opengever/task/response.py
  opengever/task/tests/test_response.py
Labels: Backport needed

#5178 Fix create zip for concurrent callback requests.
  docs/HISTORY.txt
  opengever/meeting/browser/meetings/zipexport.py
  opengever/meeting/browser/resources/zip_export_app.js
  opengever/meeting/tests/test_meeting_zipdemand.py
  opengever/meeting/tests/test_meeting_zipexport_callback.py
  opengever/meeting/zipexport.py
Labels: Backport needed

#5194 Bump docxcompose to 1.0.0a15 for bugfixes.
  docs/HISTORY.txt
  versions.cfg
Labels: Backport needed

#5203 Set changed date on ObjectAdded instead of ObjectCreatedEvent.
  docs/HISTORY.txt
  opengever/base/configure.zcml
  opengever/base/handlers.py
  opengever/base/tests/test_changed_date.py
Labels: Backport needed

#5212 Remove plonetheme.teamraum upgradesteps.
  docs/HISTORY.txt
  plonetheme/teamraum/configure.zcml
  plonetheme/teamraum/upgrades/__init__.py
  plonetheme/teamraum/upgrades/configure.zcml
  plonetheme/teamraum/upgrades/default/__init__.py
  plonetheme/teamraum/upgrades/default/configure.zcml
  plonetheme/teamraum/upgrades/default/profiles/2001/viewlets.xml
  plonetheme/teamraum/upgrades/default/profiles/2002/cssregistry.xml
  plonetheme/teamraum/upgrades/default/profiles/2003/cssregistry.xml
  plonetheme/teamraum/upgrades/default/profiles/2004/cssregistry.xml
  plonetheme/teamraum/upgrades/default/profiles/2005/mimetypes.xml
  plonetheme/teamraum/upgrades/default/profiles/2006/theme.xml
  plonetheme/teamraum/upgrades/default/profiles/2008/.gitkeep
  plonetheme/teamraum/upgrades/default/profiles/2010/jsregistry.xml
  plonetheme/teamraum/upgrades/default/profiles/2011/jsregistry.xml
  plonetheme/teamraum/upgrades/default/profiles/2012/jsregistry.xml
  plonetheme/teamraum/upgrades/default/to2001.py
  plonetheme/teamraum/upgrades/default/to2002.py
  plonetheme/teamraum/upgrades/default/to2003.py
  plonetheme/teamraum/upgrades/default/to2005.py
  plonetheme/teamraum/upgrades/default/to2009.py
  plonetheme/teamraum/upgrades/gever/__init__.py
  plonetheme/teamraum/upgrades/gever/configure.zcml
  plonetheme/teamraum/upgrades/gever/profiles/2007/cssregistry.xml
  plonetheme/teamraum/upgrades/gever/profiles/2008/skins.xml
  plonetheme/teamraum/upgrades/gever/profiles/3200/jsregistry.xml
  plonetheme/teamraum/upgrades/gever/profiles/3300/cssregistry.xml
Labels: Backport needed

#5188 Ergänzung Kapitel Sitzungs-App
  docs/public/user-manual/img/media/img-sitzungs-app-1.png
  docs/public/user-manual/img/media/img-sitzungs-app-10.png
  docs/public/user-manual/img/media/img-sitzungs-app-2.png
  docs/public/user-manual/img/media/img-sitzungs-app-3.png
  docs/public/user-manual/img/media/img-sitzungs-app-4.png
  docs/public/user-manual/img/media/img-sitzungs-app-5.png
  docs/public/user-manual/img/media/img-sitzungs-app-6.png
  docs/public/user-manual/img/media/img-sitzungs-app-7.png
  docs/public/user-manual/img/media/img-sitzungs-app-8.png
  docs/public/user-manual/img/media/img-sitzungs-app-9.png
  docs/public/user-manual/index.rst
  docs/public/user-manual/sitzungs-app/aktualisieren.rst
  docs/public/user-manual/sitzungs-app/benachrichtigen.rst
  docs/public/user-manual/sitzungs-app/herunterladen.rst
  docs/public/user-manual/sitzungs-app/hochladen.rst
  docs/public/user-manual/sitzungs-app/index.rst
  docs/public/user-manual/sitzungs-app/notizen.rst
  docs/public/user-manual/sitzungs-app/zusammenstellen.rst
Labels: Documentation

#5213 Korrektur diverser Schreibfehler
  docs/public/admin-manual/rollenmodell.rst
  docs/public/user-manual/dokumente/anschauen.rst
  docs/public/user-manual/standardablaeufe.rst
Labels: Documentation

#5228 Convert all opengever.advancedsearch tests to integration test.
  opengever/advancedsearch/tests/test_search.py
  opengever/testing/integration_test_case.py
Labels: Testing

#5232 Fix flaky relation tests
  opengever/base/tests/test_relations.py
Labels: Testing

#5233 Convert trash tests to integration tests
  opengever/testing/integration_test_case.py
  opengever/trash/tests/test_catalog.py
  opengever/trash/tests/test_remove.py
  opengever/trash/tests/test_remove_conditions.py
  opengever/trash/tests/test_trash.py
Labels: Testing
