Repository 4teamwork/opengever.core, pull requests merged in 2018-05, with the labels that each got.

#4251 Bump docxcompose to 1.0.0a9 for bugfixes.
  docs/HISTORY.txt
  versions.cfg
Labels: Backport needed

#4287 Fetch archivist group members from ogds.
  docs/HISTORY.txt
  opengever/disposition/disposition.py
  opengever/disposition/tests/test_activities.py
Labels: Aussonderung, Benachrichtigung

#4318 Fix too long physical_path value issue.
  docs/HISTORY.txt
  opengever/core/upgrades/20180517160709_change_physical_path_column_type/__init__.py
  opengever/core/upgrades/20180517160709_change_physical_path_column_type/upgrade.py
  opengever/globalindex/model/task.py
  opengever/meeting/model/committee.py
  opengever/meeting/model/proposal.py
Labels: Backport needed

#4310 Update Bereich Dokument einchecken
  docs/public/user-manual/dokumente/bearbeiten.rst
  docs/public/user-manual/img/media/img-dokumente-10.png
Labels: Documentation

#4311 Update, dass Teamaufgaben durch Admin erfasst werden können
  docs/public/user-manual/aufgaben/teamaufgaben.rst
Labels: Documentation

#4308 Ergänzung Kapitel Favoriten
  docs/public/user-manual/favoriten.rst
  docs/public/user-manual/img/media/img-favoriten-1.png
  docs/public/user-manual/img/media/img-favoriten-2.png
  docs/public/user-manual/img/media/img-favoriten-3.png
  docs/public/user-manual/img/media/img-favoriten-4.png
  docs/public/user-manual/index.rst
Labels: Documentation

#4325 Update Favoriten-Kapitel auf Basis Inputs Erich
  docs/public/user-manual/favoriten.rst
Labels: Documentation

#4378 Verlinkung Aufgabenworkflow mit Kapitel Aufgabe erstellen
  docs/public/user-manual/aufgaben/aufgaben-workflow.rst
  docs/public/user-manual/aufgaben/erstellen.rst
  docs/public/user-manual/aufgaben/index.rst
Labels: Documentation
