Repository 4teamwork/opengever.core, pull requests merged in 2019-07, with the labels that each got.

#5774 Bump plone.restapi to latest version 4.3.0.
  docs/HISTORY.txt
  docs/public/dev-manual/api/docs_changelog.rst
  docs/public/dev-manual/api/summaries.rst
  opengever/api/catalog.py
  opengever/api/configure.zcml
  opengever/api/fields.py
  opengever/api/livesearch.py
  opengever/api/overrides.zcml
  opengever/api/summary.py
  opengever/api/tests/test_journal.py
  opengever/api/tests/test_repository.py
  opengever/api/tests/test_search.py
  opengever/api/tests/test_summary.py
  opengever/base/contentlisting.py
  opengever/inbox/tests/test_api_support.py
  opengever/inbox/transition.py
  opengever/task/tests/test_response_syncer.py
  setup.py
  versions.cfg
Labels: api-change

#5761 Add optional facet values and counts search to listing endpoint
  docs/HISTORY.txt
  docs/public/dev-manual/api/listings.rst
  opengever/api/listing.py
  opengever/api/tests/test_listing.py
Labels: Documentation

#5777 @listing endpoint: Exclude searchroot from Solr results.
  docs/HISTORY.txt
  opengever/api/listing.py
  opengever/api/tests/test_listing.py
Labels: Solr

#5808 Add workspace todo type
  README.rst
  docs/HISTORY.txt
  docs/public/dev-manual/api/listings.rst
  docs/public/dev-manual/api/workspace/index.rst
  docs/public/dev-manual/api/workspace/todos.rst
  opengever/api/listing.py
  opengever/api/tests/test_listing.py
  opengever/contentstats/tests/test_content_stats_integration.py
  opengever/core/locales/de/LC_MESSAGES/opengever.core.po
  opengever/core/locales/fr/LC_MESSAGES/opengever.core.po
  opengever/core/locales/opengever.core.pot
  opengever/core/profiles/default/types.xml
  opengever/core/profiles/default/types/opengever.workspace.todo.xml
  opengever/core/profiles/default/types/opengever.workspace.workspace.xml
  opengever/core/profiles/default/workflows.xml
  opengever/core/profiles/default/workflows/opengever_workspace_todo/.gitignore
  opengever/core/profiles/default/workflows/opengever_workspace_todo/definition.xml
  opengever/core/profiles/default/workflows/opengever_workspace_todo/specification.txt
  opengever/core/upgrades/20190710151706_install_workspace_todo_type/__init__.py
  opengever/core/upgrades/20190710151706_install_workspace_todo_type/types.xml
  opengever/core/upgrades/20190710151706_install_workspace_todo_type/types/opengever.workspace.todo.xml
  opengever/core/upgrades/20190710151706_install_workspace_todo_type/types/opengever.workspace.workspace.xml
  opengever/core/upgrades/20190710151706_install_workspace_todo_type/upgrade.py
  opengever/core/upgrades/20190710151706_install_workspace_todo_type/workflows.xml
  opengever/core/upgrades/20190710151706_install_workspace_todo_type/workflows/opengever_workspace_todo/definition.xml
  opengever/latex/tests/test_dossierjournal.py
  opengever/testing/builders/dx.py
  opengever/testing/fixtures.py
  opengever/workspace/browser/tabbed.py
  opengever/workspace/browser/tabs.py
  opengever/workspace/interfaces.py
  opengever/workspace/locales/de/LC_MESSAGES/opengever.workspace.po
  opengever/workspace/locales/fr/LC_MESSAGES/opengever.workspace.po
  opengever/workspace/locales/opengever.workspace.pot
  opengever/workspace/tests/test_todo.py
  opengever/workspace/tests/test_workspace_workspace.py
  opengever/workspace/todo.py
Labels: teamraum

#5841 Include actor_id and actor_label in @notifications endpoint responses.
  docs/HISTORY.txt
  docs/public/dev-manual/api/notifications.rst
  opengever/activity/model/notification.py
  opengever/api/tests/test_notifications.py
Labels: api-change

#5837 Rework SIP Package generation and download
  docs/HISTORY.txt
  opengever/disposition/browser/configure.zcml
  opengever/disposition/browser/ech0160.py
  opengever/disposition/browser/overview.py
  opengever/disposition/disposition.py
  opengever/disposition/handlers.py
  opengever/disposition/locales/de/LC_MESSAGES/opengever.disposition.po
  opengever/disposition/locales/fr/LC_MESSAGES/opengever.disposition.po
  opengever/disposition/locales/opengever.disposition.pot
  opengever/disposition/tests/test_disposition.py
  opengever/disposition/tests/test_ech0160export.py
  opengever/disposition/tests/test_overview.py
Labels: Aussonderung
