Repository 4teamwork/opengever.core, pull requests merged in 2019-06, with the labels that each got.

#5698 Drop no longer working oneoffixx upgrade.
  docs/HISTORY.txt
  opengever/core/upgrades/20180912145057_add_a_registry_setting_for_oneoffixx_baseurl/__init__.py
  opengever/core/upgrades/20180912145057_add_a_registry_setting_for_oneoffixx_baseurl/registry.xml
  opengever/core/upgrades/20180912145057_add_a_registry_setting_for_oneoffixx_baseurl/upgrade.py
Labels: Backport needed

#5702 Add note to meeting docu about Seitennummerierung von Protokollen.
  docs/public/user-manual/spv/sitzung-vorbereiten.rst
Labels: Documentation

#5711 Do not sync deadline modifications to forwarding predecessors.
  docs/HISTORY.txt
  opengever/task/response_syncer/deadline.py
  opengever/task/tests/test_deadline_modification.py
Labels: Backport needed

#5661 Docs: Update nightly cron jobs example
  docs/intern/operations/allgemein.rst
Labels: Documentation

#5728 Fix validation of resolve preconditions in archive form
  docs/HISTORY.txt
  opengever/dossier/archive.py
  opengever/dossier/resolve.py
  opengever/dossier/tests/test_archiver.py
Labels: Backport needed

#5731 Add release notes for the 2019.3 release.
  docs/public/release-notes/index.rst
  docs/public/release-notes/release-2019.3.rst
Labels: Documentation

#5736 Dokumentation zu den ausgecheckten Dokumente aktualisiert und verbessert.
  docs/public/user-manual/dokumente/finden.rst
  docs/public/user-manual/dokumente/index.rst
  docs/public/user-manual/dokumente/versionen.rst
  docs/public/user-manual/img/media/img-dokumente-14.png
  docs/public/user-manual/kuerzlich_bearbeitet.rst
Labels: Documentation

#5750 REST-API: Handle workspace invitations
  docs/HISTORY.txt
  opengever/api/configure.zcml
  opengever/api/participation.py
  opengever/api/tests/test_participation.py
  opengever/api/tests/test_workspace.py
  opengever/api/workspace.py
  opengever/workspace/participation/browser/my_invitations.py
  opengever/workspace/tests/test_my_invitations.py
Labels: API, teamraum

#5756 Add fields available in listing endpoint for each type to documentation.
  docs/HISTORY.txt
  docs/public/dev-manual/api/listings.rst
  docs/public/dev-manual/api/webactions.rst
  opengever/api/listing.py
Labels: Documentation
