Repository 4teamwork/opengever.core, pull requests merged in 2019-03, with the labels that each got.

#5448 Readd Office macro files into Office Connector editable MIME types
  docs/HISTORY.txt
  opengever/officeconnector/mimetypes.py
Labels: Backport needed

#5457 Ergänzungen bei SPV zu inaktiver Mitgliedschaft
  docs/public/user-manual/eingangskorb.rst
  docs/public/user-manual/img/media/img-spvupdate-43.png
  docs/public/user-manual/index.rst
  docs/public/user-manual/spv/sitzung-durchfuehren.rst
Labels: Documentation

#5454 Readd Office template, macro, stencil files into Office Connector editable MIME types
  docs/HISTORY.txt
  opengever/document/extra_mimetypes.py
  opengever/officeconnector/mimetypes.py
Labels: Backport needed

#5475 Make sure end date is reindexed when resolving/reactivating a dossier.
  docs/HISTORY.txt
  opengever/core/upgrades/20190307102922_reindex_dossier_end_date/__init__.py
  opengever/core/upgrades/20190307102922_reindex_dossier_end_date/upgrade.py
  opengever/dossier/base.py
  opengever/dossier/resolve.py
  opengever/dossier/tests/test_activate.py
  opengever/dossier/tests/test_resolve.py
  opengever/testing/integration_test_case.py
Labels: Backport needed

#5476 Make sure task and journal PDFs object_provides index is up to date
  docs/HISTORY.txt
  opengever/core/upgrades/20190307102922_reindex_dossier_end_date/upgrade.py
  opengever/core/upgrades/20190307132714_fix_task_and_journal_pdf_object_provides/__init__.py
  opengever/core/upgrades/20190307132714_fix_task_and_journal_pdf_object_provides/upgrade.py
  opengever/dossier/resolve.py
  opengever/dossier/tests/test_resolve.py
Labels: Backport needed

#5490 Fix performance issue with search root exclusion in tabbed view listings
  docs/HISTORY.txt
  opengever/tabbedview/catalog_source.py
Labels: Backport needed

#5497 Korrektur Schreibfehler
  docs/public/user-manual/sitzungs-app/aktualisieren.rst
  docs/public/user-manual/sitzungs-app/benachrichtigen.rst
  docs/public/user-manual/sitzungs-app/herunterladen.rst
  docs/public/user-manual/sitzungs-app/hochladen.rst
  docs/public/user-manual/sitzungs-app/zusammenstellen.rst
Labels: Documentation

#5499 Update Infos zu Office Connector
  docs/public/user-manual/dokumente/bearbeiten.rst
Labels: Documentation

#5492 Update plone.rest api to 3.7.2.
  docs/HISTORY.txt
  versions.cfg
Labels: API, UI, api-change

#5512 Fix upgrade step that reindexes object_provides for PDFs so it performs better
  docs/HISTORY.txt
  opengever/core/upgrades/20190307132714_fix_task_and_journal_pdf_object_provides/upgrade.py
Labels: Backport needed

#5509 Notes für .docx und spez. Konfiguration
  docs/public/admin-manual/docproperties/insert.rst
  docs/public/admin-manual/docproperties/list.rst
Labels: Documentation

#5517 Add solrsearch REST API endpoint.
  docs/HISTORY.txt
  docs/public/dev-manual/api/searching.rst
  opengever/api/configure.zcml
  opengever/api/solrsearch.py
  opengever/api/tests/test_solrsearch.py
Labels: api-change
